// <auto-generated />
using System;
using AzureAPI.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250912103005_AddFightCardType")]
    partial class AddFightCardType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzureAPI.Objects.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AzureAPI.Objects.Fight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("BlueBodyStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueClinchStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<int>("BlueCornerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("BlueDistanceStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueGroundStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueHeadStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueKnockdowns")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueLegStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<short>("BlueOdds")
                        .HasColumnType("SMALLINT");

                    b.Property<byte[]>("BlueSubAttempts")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("BlueTakedowns")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<short>("BlueTotalKnockdowns")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("BlueTotalStrikes")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("BlueTotalSubAttempts")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("BlueTotalTakedowns")
                        .HasColumnType("SMALLINT");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTitleFight")
                        .HasColumnType("bit");

                    b.Property<byte>("MethodOfVictory")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RedBodyStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedClinchStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<int>("RedCornerId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RedDistanceStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedGroundStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedHeadStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedKnockdowns")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedLegStrikes")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<short>("RedOdds")
                        .HasColumnType("SMALLINT");

                    b.Property<byte[]>("RedSubAttempts")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<byte[]>("RedTakedowns")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("BINARY(5)")
                        .IsFixedLength();

                    b.Property<short>("RedTotalKnockdowns")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("RedTotalStrikes")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("RedTotalSubAttempts")
                        .HasColumnType("SMALLINT");

                    b.Property<short>("RedTotalTakedowns")
                        .HasColumnType("SMALLINT");

                    b.Property<byte>("Round")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<byte>("WeightClass")
                        .HasColumnType("tinyint");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("AzureAPI.Objects.Fighter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Height")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("LegReach")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Reach")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<byte>("WeightClass")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Fighters");
                });
#pragma warning restore 612, 618
        }
    }
}
